// ALT+SHIFT+F = INDENTAÇÃO
// CTRL+B = TIRA ou MOSTRA A BARRA LATERAL ESQUERDA DO VISUAL STUDIO
// CTRL+J = TIRA ou MOSTRA A BARRA DE DEBUG
// CTRL+N = CRIA UM NOVO DOCUMENTO
// CTRL+S = SALVA O QUE ESTÁ SENDO FEITO
// CTRL+P = BUSCA SEUS SCRIPT/PROJETOS
// ALT+SHIFT+ SETA PRA CIMA OU BAIXO = DUBLICA AS INFORMAÇÕES QUE ESTÃO SELECIONADAS
// CTRL+F = CLIQUE NA PALAVRA QUE VOCÊ QUER QUE BUSQUE POR ELA. E F3 VAI NAVEGANDO ENTRE A PALAVRA SELECIONADA. SHIFT+F3 ELE VOLTA
// CTRL+F2 = CASO VOCÊ PRECISE TROCAR O NOME DE ALGUMA VARIÁVEL EM MASSA
// CTRL + K+ C = COMENTA O SCRIPT, PARA DESFAZER UTILIZE O COMANDO CTRL +K +U
// ALT + SETA PRA CIMA OU BAIXO = MOVIMENTA A LINHA QUANDO VOCÊ CLICA EM CIMA DE QUALQUER INFORMAÇÃO CONTIDA NELA
// CRTL + SHIFT + K = APAGA A LINHA
// User Function : é 8 caracteres que podemos criar, ao total fica 10 devido o (U_)
